#!name=All-in-One by Quyenle
#!desc=Spotify Pre, Locket Gold By Quyenle 

[General]
user-agent = Locket/1.0.0 (iPhone; iOS 26; Scale/3.00)

[Script]

# --- Locket Gold ---
revenuecat = type=http-response, pattern=^https:\/\/api\.revenuecat\.com\/.*\/(receipts$|subscribers\/[^/]+$), script-path=https://raw.githubusercontent.com/Ohshjt/Premium/refs/heads/main/js/Locket/locketql.js, requires-body=true, max-size=-1, timeout=120
deleteHeader = type=http-request, pattern=^https:\/\/api\.revenuecat\.com\/.*\/(receipts|subscribers), script-path=https://raw.githubusercontent.com/Ohshjt/Premium/refs/heads/main/js/Locket/deleteHeader.js, timeout=120

# --- Spotify Premium ---
spotify-json = type=http-request,pattern=^https:\/\/spclient\.wg\.spotify\.com\/(artistview\/v1\/artist|album-entity-view\/v2\/album)\/,requires-body=0,script-path=https://raw.githubusercontent.com/Ohshjt/Premium/refs/heads/main/js/Spotify/spotify-json.js
spotify-proto = type=http-response,pattern=^https:\/\/spclient\.wg\.spotify\.com\/(bootstrap\/v1\/bootstrap|user-customization-service\/v1\/customize)$,requires-body=1,binary-body-mode=1,max-size=-1,script-path=https://raw.githubusercontent.com/Ohshjt/Premium/refs/heads/main/js/Spotify/spotify-proto.js,script-update-interval=0,timeout=60

# --- OldRoll LifetimeVIP ---
OldRoll=type=http-response,pattern=^https?:\/\/buy\.itunes\.apple\.com\/verifyReceipt$,requires-body=1,script-path=https://raw.githubusercontent.com/Ohshjt/Premium/refs/heads/main/js/OldRoll/LifetimeVIP.js

# --- Picsart ---
http-response ^https://api\.revenuecat\.com/.+/(receipts$|subscribers/[^/]+$) script-path=https://raw.githubusercontent.com/Ohshjt/Premium/refs/heads/main/js/Picsart/crack.js, requires-body=true, timeout=5, tag=Crack
http-request https://api.picsart.com/gw-v2/shop/subscription/apple/purchases script-path=https://raw.githubusercontent.com/Ohshjt/Premium/refs/heads/main/js/Picsart/PicsArt.js, requires-body=true, timeout=5, tag=PicsArt

# --- VSCO Pro ---
http-response ^https://api\.revenuecat\.com/.+/(receipts$|subscribers/[^/]+$) script-path=https://raw.githubusercontent.com/Ohshjt/Premium/refs/heads/main/js/VSCO/crack.js, requires-body=true, timeout=5, tag=Crack
http-request ^https://api.revenuecat.com/.+/(receipts$|subscribers/?(.*?)*$) script-path=https://raw.githubusercontent.com/Ohshjt/Premium/refs/heads/main/js/VSCO/VSCO.js, requires-body=true, timeout=5, tag=VSCO

[MITM]
hostname = %APPEND% buy.itunes.apple.com, spclient.wg.spotify.com, api.revenuecat.com, raw.githubusercontent.com, api.picsart.com, buy.itunes.apple.com
