#!name=Picsart_Xwuan
#!desc=crack by ie.1w3n

[General]
bypass-system = true
skip-proxy = *.local, *.crashlytics.com
tun-excluded-routes = 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12

[Script]
http-response ^https://api\.revenuecat\.com/.+/(receipts$|subscribers/[^/]+$) script-path=https://raw.githubusercontent.com/Xwuan19/Premium/refs/heads/main/js/Picsart/crack.js, requires-body=true, timeout=5, tag=Crack
http-request https://api.picsart.com/gw-v2/shop/subscription/apple/purchases script-path=https://raw.githubusercontent.com/Xwuan19/Premium/refs/heads/main/js/Picsart/PicsArt.js, requires-body=true, timeout=5, tag=PicsArt

[MITM]
hostname = api.revenuecat.com, buy.itunes.apple.com, api.picsart.com
