[Proxy]
US-Nodes = url = sub://aHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL0Vwb2Rvbmlvcy92MnJheS1jb25maWdzL3JlZnMvaGVhZHMvbWFpbi9BbGxfQ29uZmlnc19TdWIudHh0

---
[Proxy Group]
Auto-US = url-test, US-Nodes, url=http://www.gstatic.com/generate_204, interval=600, tolerance=150

---
[Rule]
# Một số quy tắc cơ bản để chuyển hướng lưu lượng
# Nếu bạn đã có quy tắc riêng, bạn có thể bỏ qua phần này
# SỬ DỤNG LẠI TÊN NHÓM PROXY ĐÃ KHAI BÁO Ở TRÊN (ví dụ: Auto-US)
FINAL,Auto-US
